apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hubnegocios

resources:
  - namespace.yaml
  - postgres.yaml
  - minio.yaml
  - redis.yaml
  - api.yaml
  - web.yaml
  - admin.yaml
  - cloudflared.yaml
  - pdbs.yaml
