// Every user-visible string in the admin console lives here. Hub Negocios UDP
// is Spanish-only — no bilingual CopyShape<T> split like other admin consoles
// in this family.

export const adminPageCopy = {
  dateLocale: "es-CL",
  title: "Panel de administración",
  loginTitle: "Panel de gestión",
  loginHelp:
    "Ingresa con tu cuenta @udp.cl (Google), un passkey, o la cuenta de emergencia del superadmin.",
  email: "Email",
  password: "Contraseña",
  signIn: "Entrar al admin",
  passkey: "Ingresar con passkey",
  signOut: "Salir",
  loading: "Cargando panel",
  permissionError: "No tienes permisos de administrador",
  loadError: "No se pudo cargar el panel",
  tabs: {
    panel: "Panel",
    faqs: "Preguntas frecuentes",
    articles: "Artículos",
    gallery: "Galería",
    team: "Equipo",
    contact: "Contacto",
    intake: "Ingreso",
    clinics: "Clínicas",
    adminUsers: "Usuarios admin",
    settings: "Configuración",
    audit: "Auditoría",
    account: "Mi cuenta",
  },
  navGroups: {
    clinic: "Mi clínica",
    contact: "Contacto",
    system: "Sistema",
  },
  sidebar: {
    collapse: "Colapsar menú",
    expand: "Expandir menú",
    openMenu: "Abrir menú",
    closeMenu: "Cerrar menú",
  },
  common: {
    save: "Guardar",
    create: "Crear",
    edit: "Editar",
    delete: "Eliminar",
    cancel: "Cancelar",
    close: "Cerrar",
    confirm: "Confirmar",
    saving: "Guardando…",
    deleting: "Eliminando…",
    upload: "Subir imagen",
    uploading: "Subiendo…",
    publish: "Publicar",
    published: "Publicado",
    draft: "Borrador",
    active: "Activo",
    inactive: "Inactivo",
    status: "Estado",
    actions: "Acciones",
    clinic: "Clínica",
    allClinics: "Todas las clínicas",
    noData: "No hay datos para mostrar.",
    confirmDelete: "¿Confirmas que quieres eliminar este elemento?",
    sessionExpired: "Tu sesión expiró. Vuelve a entrar al admin.",
    actionFailed: (detail: string) => `No se pudo completar la acción: ${detail}`,
  },
  panelScreen: {
    title: "Resumen",
    faqs: "Preguntas frecuentes",
    articles: "Artículos",
    galleryAlbums: "Álbumes de galería",
    teamMembers: "Miembros del equipo",
    pendingInquiries: "Consultas pendientes",
    byClinic: "Por clínica",
  },
  faqsPanel: {
    title: "Preguntas frecuentes",
    newFaq: "Nueva pregunta",
    editFaq: "Editar pregunta",
    question: "Pregunta",
    answer: "Respuesta",
    order: "Orden",
    reorderHint: "Arrastra las filas o usa los botones para reordenar.",
  },
  articlesPanel: {
    feature: "Destacar en la portada",
    featured: "Destacada",
    title: "Artículos",
    newArticle: "Nuevo artículo",
    editArticle: "Editar artículo",
    articleTitle: "Título",
    slug: "Slug",
    excerpt: "Extracto",
    body: "Contenido",
    coverImage: "Imagen de portada",
    author: "Autor",
    publishedAt: "Fecha de publicación",
  },
  galleryPanel: {
    title: "Galería",
    newAlbum: "Nuevo álbum",
    editAlbum: "Editar álbum",
    albumTitle: "Título del álbum",
    description: "Descripción",
    coverImage: "Imagen de portada",
    photos: "Fotos",
    addPhoto: "Agregar foto",
    caption: "Descripción de la foto",
  },
  teamPanel: {
    title: "Equipo",
    newMember: "Nuevo integrante",
    editMember: "Editar integrante",
    fullName: "Nombre completo",
    roleTitle: "Cargo",
    bio: "Biografía",
    photo: "Foto",
    email: "Email",
  },
  contactPanel: {
    title: "Consultas de contacto",
    name: "Nombre",
    email: "Email",
    phone: "Teléfono",
    message: "Mensaje",
    internalNotes: "Notas internas",
    statuses: {
      new: "Nueva",
      in_progress: "En curso",
      closed: "Cerrada",
    },
  },
  intakePanel: {
    title: "Solicitudes de ingreso",
    fullName: "Nombre",
    rut: "RUT",
    email: "Email",
    phone: "Teléfono",
    caseType: "Tipo de caso",
    caseDescription: "Descripción del caso",
    hasDocumentation: "Documentación disponible",
    internalNotes: "Notas internas",
    statuses: {
      new: "Nueva",
      in_review: "En revisión",
      accepted: "Aceptada",
      rejected: "Rechazada",
      closed: "Cerrada",
    },
  },
  clinicsPanel: {
    title: "Clínicas",
    editClinic: "Editar clínica",
    name: "Nombre",
    shortDescription: "Descripción breve",
    description: "Descripción",
    icon: "Icono",
    colorPrimary: "Color principal",
    image: "Foto del equipo completo",
    contactEmail: "Email de contacto",
    order: "Orden",
  },
  adminUsersPanel: {
    title: "Usuarios admin",
    newUser: "Invitar usuario",
    editUser: "Editar usuario",
    email: "Email",
    firstName: "Nombre",
    lastName: "Apellido",
    role: "Rol",
    roles: {
      superadmin: "Superadmin",
      clinic_admin: "Admin de clínica",
    },
    clinic: "Clínica",
    permissions: "Permisos",
    status: "Estado",
  },
  settingsPanel: {
    title: "Configuración",
    key: "Clave",
    value: "Valor (JSON)",
    updatedBy: "Actualizado por",
    invalidJson: "El valor debe ser JSON válido",
  },
  auditPanel: {
    title: "Auditoría",
    actor: "Actor",
    action: "Acción",
    target: "Objetivo",
    date: "Fecha",
  },
  account: {
    title: "Mi cuenta",
    profile: "Perfil",
    role: "Rol",
    permissions: "Permisos",
    allPermissions: "Acceso total",
    security: "Seguridad y acceso",
    passkeys: "Passkeys",
    passkeysHelp: "Ingresa con Touch ID, Face ID o una llave de seguridad.",
    addPasskey: "Agregar passkey",
    addingPasskey: "Agregando…",
    passkeyAdded: "Passkey agregado",
    passkeyFallback: "Passkey",
    passkeyUnsupported: "Este navegador no soporta passkeys.",
    passkeyLabel: "Nombre del passkey",
    passkeyLabelPlaceholder: "MacBook de trabajo",
    created: "Creado",
    lastUsed: "Último uso",
    never: "Nunca",
    remove: "Quitar",
    lastMethodConflict: "Es tu único método de acceso: agrega otro antes de quitarlo.",
    noPasskeys: "Aún no tienes passkeys.",
    linkedAccounts: "Cuentas vinculadas",
    connected: "Conectada",
    connect: "Conectar",
    connecting: "Conectando…",
    disconnect: "Desconectar",
    noProviders: "No hay proveedores sociales configurados.",
    loadError: "No se pudieron cargar los métodos de acceso.",
  },
  errorPages: {
    errorTitle: "Error en el panel",
    errorBody: "Algo no funcionó correctamente. Hemos registrado el error e investigaremos inmediatamente.",
    retry: "Intentar nuevamente",
    backToPanel: "Volver al panel",
    persistHelp: "Si el problema persiste, recarga la página o contacta soporte.",
    notFoundTitle: "Página no encontrada",
    notFoundBody: "La sección que buscas no existe. Verifica la URL o vuelve al panel de administración.",
    goToPanel: "Ir al Panel",
    signOut: "Cerrar sesión",
    notFoundHelp: "Si sigues viendo este error, contacta al equipo de soporte.",
    forbiddenTitle: "Sin autorización",
    forbiddenBody: "Tu rol de usuario no tiene permiso para acceder a este recurso. Contacta al administrador si crees que es un error.",
    globalTitle: "Fallo en el panel",
    globalBody: "Se produjo un error crítico. Por favor recarga la página para continuar.",
    reload: "Recargar",
  },
} as const;

export type AdminPageCopy = typeof adminPageCopy;
